# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2010"
  config.vm.synced_folder "./data", "/mnt/host_data", mount_options: ["ro"]
  config.vm.hostname = "zfs"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.check_guest_additions = true
    vb.name = "zfs"
  end

  disks = {
    "zfs_striped_0" => {:size => "10GB"},
    "zfs_mirror_0" => {:size => "10GB"},
    "zfs_mirror_1" => {:size => "10GB"}
  }

  disks.each do |name, info|
    config.vm.disk :disk, size: info[:size], name: name
  end

  config.vm.provision :shell, path: "bootstrap.sh"
end
