# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
  { :hostname => 'master', :ip => '172.16.0.42'},
  { :hostname => 'worker',  :ip => '172.16.0.43'}
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "generic/centos8"
      nodeconfig.vm.synced_folder "./data", "/mnt/host_data", mount_options: ["ro"]
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network :private_network, ip: node[:ip]
      nodeconfig.vm.provider "virtualbox" do |vb|
        vb.memory = "8192"
        vb.cpus = 3
        vb.check_guest_additions = true
        vb.name = node[:hostname]
      end
    end
  end
end
